name: rtd-test-code
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - numpy
  - scipy
  - librosa
  - seaborn
  - soundfile
  - ffmpeg
  - torch
  - praat-parselmouth
  - ipython
